### ISSUE TITLE
AWS auth fails for temporary cedentials

### ISSUE THREAD

**Issue by martinka** [Colin-b/httpx_auth#14]
I tested with the latest versions and the aws auth is failing for temporary credentials ( those that require a session token).  The version from the original PR I pushed still works so its not a change in AWS.  I will take a look soon ( next couple of days) to see if I can figure out what broke it.

**Comment by Colin-b** [comment]
Do you have a link to something I could try out myself (as in I would only need to create a free temporary account to try it)

**Comment by martinka** [comment]
Let me see if I can find a case that works with a free account.  The basic approach is to create a EC2 instance with an IAM role it needs for access to some other service. Then you use boto3.Session().get_credentials() to get a temporary set of credentials for the role.  
You can run an EC2 instance in the free tier for some time.  
Anyway I will see what I can come up with for you.
