### ISSUE TITLE
Authorization header got assigned wrongly.

### ISSUE THREAD

**Issue by AmericanY** [Colin-b/httpx_auth#29]
https://github.com/Colin-b/httpx_auth/blob/2580abcfdedd56f8637add8e4529344afad7c0b0/httpx_auth/aws.py#L91

The value for `authorization` is actually getting assigned wrongly.

as am getting: `'authorization': '[secure]'`

But I've tried to print the `auth_str` and it's printed correctly.

**Comment by AmericanY** [comment]
otherwise `httpx` library is wrapping the value as `'[secure]'`

**Comment by Colin-b** [comment]
I am not sure what the issue is actually, httpx is obfuscating the authorization header to avoid leaking credentials in logs I assume, but the correct value is supposed to be used. Please reopen if there is something to investigate. Thanks again.
