### ISSUE TITLE
Indicate that the project is typed

### ISSUE THREAD

**Issue by nymous** [Colin-b/httpx_auth#43]
Hello!

Thank you for this project, it greatly simplifies my httpx calls against OAuth protected APIs, without having to deal with secrets exchange and response parsing and everything ^^

While running mypy I saw `Skipping analyzing "httpx_auth": found module but no type hints or library stubs`. While looking at the code I think everything is typed, so you could indicate it to type checkers to improve everyone's code safety!
It should be as simple as adding an empty `py.typed` file, like in [Pydantic](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/py.typed) or in [FastAPI](https://github.com/tiangolo/fastapi/blob/master/fastapi/py.typed).

You can also add the PyPI classifier `Typing :: Typed` (see in [FastAPI](https://github.com/tiangolo/fastapi/blob/master/pyproject.toml#L21)).

I can open a PR with this change if you want! :wink:

**Comment by Colin-b** [comment]
Hello @nymous ,

Sure go ahead with the PR, it will be a nice touch :)

Thanks

**Comment by nymous** [comment]
Just to see how well it would work, I added the `py.typed` file in the virtualenv of my application. When running mypy (in strict mode) I stumbled upon the following issue:
> Module "httpx_auth" does not explicitly export attribute "OAuth2ClientCredentials"; implicit reexport disabled

This error also happens when using pyright with default configuration, and is because of this
> This flag changes the behavior to not re-export unless the item is imported using from-as or is included in `__all__`.

(seen in [this mypy docs](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport)).

To fix this would require to define in [this `__init__.py`](https://github.com/Colin-b/httpx_auth/blob/develop/httpx_auth/__init__.py) a `__all__` with everything you want to export, or to use the form `from httpx_auth.aws import AWS4Auth as AWS4Auth` for every import.
Not doing this would require end users to add this configuration to mypy (I haven't look at how to do it with pyright):
```ini
[mypy-,httpx_auth.*]
no_implicit_reexport = False
```
How do you want to approach this? Do you prefer the code to stay untouched and document the configuration? Do you want to use the `from ... import ... as ...` form?

---

Also, before adding the `py.typed` file I wanted to check if mypy was happy with the code, and... mypy found 30 issues, pyright 26 :sweat_smile: Would you be interested in a contribution to improve the internal types?
Should I start with the simple `py.typed` + PyPI classifier PR, then another for the types, with maybe a release after both?

**Comment by Colin-b** [comment]
Every contribution is more than welcome :)
Indeed I would rather have PR as small as possible, I don't mind multiple PRs at all :)

So a first one with the py.typed and the classifier, then a second one with the __all__ as in [this PR on another project](https://github.com/Colin-b/pytest_httpx/pull/57/files) ?

And If you still feel like it, feel free to address the issues mypy and pyright found in another PR after that :D

Thanks again
