### ISSUE TITLE
Would it be possible to add support for AWS?

### ISSUE THREAD

**Issue by martinka** [Colin-b/httpx_auth#5]
I am looking at using httpx and I like what you have done to add support for authentication to it here. I was wondering if you would be open to me working on and submitting a PR to add aws4auth?

**Comment by Colin-b** [comment]
Yes of course go ahead !

**Comment by martinka** [comment]
One follow up.. its pretty involved... not quite as bad as OAuth but not nothing.  do you want me to put it all in the authentication.py or should I split it out into its own file.  Or keep  a minimal Class in the authentication file and put "helper functions" in a separate file?

**Comment by Colin-b** [comment]
I guess you can put it in a dedicated file :-)
