### ISSUE TITLE
Question: Why define headers to sign

### ISSUE THREAD

**Issue by FlorianLudwig** [Colin-b/httpx_auth#50]
From reading the code of botocore it seems that they sign all headers except those in a blacklist:
```
SIGNED_HEADERS_BLACKLIST = [
    'expect',
    'user-agent',
    'x-amzn-trace-id',
]
```

`httpx_auth` on the other hand works with a include list approach.

Why?

**Comment by Colin-b** [comment]
Hi @FlorianLudwig,

Could you tell me what the issue is with this behavior?

ie: you need to exclude some header because of a specific issue?

**Comment by FlorianLudwig** [comment]
Hi @Colin-b ,

I don't have an issue or specific use case. I was just comparing what boto does with what your code does. And wondered why they behave differently.

**Comment by Colin-b** [comment]
Hi @FlorianLudwig , latest version now behaves as documented by AWS. You can specify "*" in the headers to include if you want all of them.
